/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laundryexpress;

/**
 *
 * @author eirmo
 */
public class Dry extends javax.swing.JPanel {

    /**
     * Creates new form Dry
     */
    public Dry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel3 = new javax.swing.JPanel();
        yesBtn = new javax.swing.JButton();
        dryLabel = new javax.swing.JLabel();
        yesBtn1 = new javax.swing.JButton();

        contentPanel3.setBackground(new java.awt.Color(21, 96, 130));

        yesBtn.setBackground(new java.awt.Color(255, 255, 255));
        yesBtn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        yesBtn.setForeground(new java.awt.Color(0, 0, 0));
        yesBtn.setText("YES");
        yesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnActionPerformed(evt);
            }
        });

        dryLabel.setBackground(new java.awt.Color(255, 191, 0));
        dryLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        dryLabel.setForeground(new java.awt.Color(255, 255, 255));
        dryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dryLabel.setText("DRY");

        yesBtn1.setBackground(new java.awt.Color(255, 255, 255));
        yesBtn1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        yesBtn1.setForeground(new java.awt.Color(0, 0, 0));
        yesBtn1.setText("NO");
        yesBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanel3Layout = new javax.swing.GroupLayout(contentPanel3);
        contentPanel3.setLayout(contentPanel3Layout);
        contentPanel3Layout.setHorizontalGroup(
            contentPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yesBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanel3Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(dryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        contentPanel3Layout.setVerticalGroup(
            contentPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(dryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(contentPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171))
        );

        yesBtn.getAccessibleContext().setAccessibleName("YES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(contentPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(contentPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesBtnActionPerformed

    private void yesBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton confirmBtn1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel contentPanel1;
    private javax.swing.JPanel contentPanel3;
    private javax.swing.JComboBox<String> detergentComboBox;
    private javax.swing.JComboBox<String> detergentComboBox1;
    private javax.swing.JLabel detergentLabel;
    private javax.swing.JLabel detergentLabel1;
    private javax.swing.JLabel dryLabel;
    private javax.swing.JComboBox<String> fabricComboBox;
    private javax.swing.JComboBox<String> fabricComboBox1;
    private javax.swing.JLabel fabricLabel;
    private javax.swing.JLabel fabricLabel1;
    private javax.swing.JLabel formLabel;
    private javax.swing.JLabel formLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel numberLabel1;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JTextField numberTextField1;
    private javax.swing.JLabel washLabel;
    private javax.swing.JLabel washLabel1;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JLabel weightLabel1;
    private javax.swing.JTextField weightTextField;
    private javax.swing.JTextField weightTextField1;
    private javax.swing.JButton yesBtn;
    private javax.swing.JButton yesBtn1;
    // End of variables declaration//GEN-END:variables
}
